### ISSUE TITLE
Misc bugs in on/off status of button lights

### ISSUE THREAD

**Issue by marcora** [soundwrightpro/FLIN#1]
Quantize button only lights up when shift is pressed. However, it lights up after I shift - press it. If I then press it again without shift, it goes dark again.

Also, mute and solo button do not light up when shift is pressed, as they should.

**Comment by soundwrightpro** [comment]
What version are you using?

**Comment by marcora** [comment]
Latest version from github with KK M32 controller.

**Comment by marcora** [comment]
build 1033 of FL Studio 20.7

**Comment by soundwrightpro** [comment]
Thanks. I've updated the READ ME and will be seeking a solution. Thanks. Keep the bug reports coming. You're the first. I hope you find the script useful.

**Comment by marcora** [comment]
Very much so! Keep up the good work :)

**Comment by soundwrightpro** [comment]
See version 2.9.4
